[package]
name = "rustrelli"
version = "0.1.0"
edition = "2024"
repository = "https://github.com/Rustrelli/rustrelli.git"

[dependencies]
common-game = { git = "ssh://git@github.com/unitn-ap-2025/common" }